export const menLevelThree = [
  // Topwear
  {
    name: "T-Shirts",
    categoryId: "men_t_shirts",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Casual Shirts",
    categoryId: "men_casual_shirts",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Formal Shirts",
    categoryId: "men_formal_shirts",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Sweatshirts",
    categoryId: "men_sweatshirts",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Sweaters",
    categoryId: "men_sweaters",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Jackets",
    categoryId: "men_jackets",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Blazzers & Coats",
    categoryId: "men_blazzers_and_coats",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Suits",
    categoryId: "men_suits",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Rain Jackets",
    categoryId: "men_rain_jackets",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Indian & Festive Wear",
    categoryId: "men_indian_and_festive_wear",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Kurtas & Kurta Sets",
    categoryId: "men_kurtas_and_kurta_sets",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Sherwanis",
    categoryId: "men_sherwanis",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Nehru Jackets",
    categoryId: "men_nehrus_jackets",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },
  {
    name: "Dhotis",
    categoryId: "men_dhotis",
    parentCategoryName: "Topwear",
    parentCategoryId: "men_topwear",
    level: 3,
  },

  //   Bottomwear
  {
    name: "Jeans",
    categoryId: "men_jeans",
    parentCategoryName: "Bottomwear",
    parentCategoryId: "men_bottomwear",
    level: 3,
  },
  {
    name: "Casual Trousers",
    categoryId: "men_casual_trousers",
    parentCategoryName: "Bottomwear",
    parentCategoryId: "men_bottomwear",
    level: 3,
  },
  {
    name: "Formal Trousers",
    categoryId: "men_formal_trousers",
    parentCategoryName: "Bottomwear",
    parentCategoryId: "men_bottomwear",
    level: 3,
  },
  {
    name: "Shorts",
    categoryId: "men_shorts",
    parentCategoryName: "Bottomwear",
    parentCategoryId: "men_bottomwear",
    level: 3,
  },
  {
    name: "Track Pants & Joggers",
    categoryId: "men_track_pants_and_joggers",
    parentCategoryName: "Bottomwear",
    parentCategoryId: "men_bottomwear",
    level: 3,
  },

  //   Innerwear & Sleepwear
  {
    name: "Briefs & Trunks",
    categoryId: "men_briefs_and_trunks",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Boxers",
    categoryId: "men_boxers",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Vests",
    categoryId: "men_vests",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Sleepwear & Loungewear",
    categoryId: "men_sleepwear_and_loungewear",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Underwear",
    categoryId: "men_underwear",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Thermals",
    categoryId: "men_thermals",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },
  {
    name: "Plus Size",
    categoryId: "men_plus_size",
    parentCategoryName: "Innerwear & Sleepwear",
    parentCategoryId: "men_innerwear_and_sleepwear",
    level: 3,
  },

  //   Footwear
  {
    name: "Casual Shoes",
    categoryId: "men_casual_shoes",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Sports Shoes",
    categoryId: "men_sports_shoes",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Formal Shoes",
    categoryId: "men_formal_shoes",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Sneakers",
    categoryId: "men_sneakers",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Sandals & Floaters",
    categoryId: "men_sandals_and_floaters",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Flip Flops",
    categoryId: "men_flip_flops",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Socks",
    categoryId: "men_socks",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },
  {
    name: "Crocks",
    categoryId: "men_crocks",
    parentCategoryName: "Footwear",
    parentCategoryId: "men_footwear",
    level: 3,
  },

  //   Personal Care And Grooming
  {
    name: "Sports & Active Wear",
    categoryId: "men_sports_and_active_wear",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Sports Sandals",
    categoryId: "men_sports_sandals",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Active T-Shirts",
    categoryId: "men_active_t_shirts",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Track Pants & Shorts",
    categoryId: "men_track_pants_and_shorts",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Tracksuits & Joggers",
    categoryId: "men_tracksuits_and_joggers",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Jackets & Sweat shirts",
    categoryId: "men_jackets_and_sweat_shirts",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Sports Accessories",
    categoryId: "men_sports_accessories",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },
  {
    name: "Swimwear",
    categoryId: "men_swimwear",
    parentCategoryName: "Personal Care And Grooming",
    parentCategoryId: "men_personal_care_and_grooming",
    level: 3,
  },

  // 👔 Men Fashion Accessories
  {
    name: "Watches",
    categoryId: "men_fashion_watches",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Belts",
    categoryId: "men_fashion_belts",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Wallets",
    categoryId: "men_fashion_wallets",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Sunglasses & Frames",
    categoryId: "men_fashion_sunglasses_and_frames",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Caps & Hats",
    categoryId: "men_fashion_caps_hats",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Ties",
    categoryId: "men_fashion_ties",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Cufflinks & Brooches",
    categoryId: "men_fashion_cufflinks_brooches",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },
  {
    name: "Scarves & Mufflers",
    categoryId: "men_fashion_scarves_mufflers",
    parentCategoryName: "Men Fashion Accessories",
    parentCategoryId: "men_fashion_accessories",
    level: 3,
  },

  // Gadgets
  {
    name: "Headphones",
    categoryId: "men_headphones",
    parentCategoryName: "Gadgets",
    parentCategoryId: "men_gadgets",
    level: 3,
  },
  {
    name: "Earphones",
    categoryId: "men_earphones",
    parentCategoryName: "Gadgets",
    parentCategoryId: "men_gadgets",
    level: 3,
  },
  {
    name: "Mobile Covers",
    categoryId: "men_mobile_covers",
    parentCategoryName: "Gadgets",
    parentCategoryId: "men_gadgets",
    level: 3,
  },
  // Bags And Backpacks
  {
    name: "Bags",
    categoryId: "men_bags",
    parentCategoryName: "Bags And Backpacks",
    parentCategoryId: "men_bags_and_backpacks",
    level: 3,
  },
  {
    name: "Backpacks",
    categoryId: "men_backpacks",
    parentCategoryName: "Bags And Backpacks",
    parentCategoryId: "men_bags_and_backpacks",
    level: 3,
  },
];
