export const womenLevelThree = [
  {
    name: "Kurtas & Suits",
    categoryId: "women_kurtas_and_suits",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Kurtis, Tunics & Tops",
    categoryId: "women_kurtis_tunics_and_tops",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Sarees",
    categoryId: "women_sarees",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Ethnic Wear",
    categoryId: "women_ethnic_wear",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Leggings, Salwars & Churidars",
    categoryId: "women_leggings_salwars_and_churidars",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Skirts & Palazzos",
    categoryId: "women_skirts_and_palazzos",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Dress Materials",
    categoryId: "women_dress_materials",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Lehenga Cholis",
    categoryId: "women_lehenga_cholis",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Dupattas & Shawls",
    categoryId: "women_dupattas_and_shawls",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Belts, Scarves & More",
    categoryId: "women_belts_scarves_and_more",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  {
    name: "Sun Glasses & More",
    categoryId: "women_sun_glasses_and_more",
    parentCategoryName: "Indian & Fusion Wear",
    parentCategoryId: "women_indian_and_fusion_wear",
    level: 3,
  },
  // Western Wear
  {
    name: "Western Wear",
    categoryId: "women_western_wear",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Dresses",
    categoryId: "women_dresses",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Tops",
    categoryId: "women_tops",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "T-shirts",
    categoryId: "women_t_shirts",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Jeans",
    categoryId: "women_jeans",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Trousers & Capris",
    categoryId: "women_trousers_and_capris",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Shorts & Skirts",
    categoryId: "women_shorts_and_skirts",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Co-ords",
    categoryId: "women_co_ords",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Playsuits",
    categoryId: "women_playsuits",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Jumpsuits",
    categoryId: "women_jumpsuits",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Shrugs",
    categoryId: "women_shrugs",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Sweaters & Sweatshirts",
    categoryId: "women_sweaters_and_sweatshirts",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Jackets & Coats",
    categoryId: "women_jackets_and_coats",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  {
    name: "Blazers & Waistcoats",
    categoryId: "women_blazers_and_waistcoats",
    parentCategoryName: "Western Wear",
    parentCategoryId: "women_western_wear",
    level: 3,
  },
  // Footwear
  {
    name: "Footwear",
    categoryId: "women_footwear",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Flats",
    categoryId: "women_flats",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Casual Shoes",
    categoryId: "women_casual_shoes",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Heels",
    categoryId: "women_heels",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Boots",
    categoryId: "women_boots",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Sneakers",
    categoryId: "women_sneakers",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  {
    name: "Sports Shoes & Floaters",
    categoryId: "women_sports_shoes_and_floaters",
    parentCategoryName: "Footwear",
    parentCategoryId: "women_footwear",
    level: 3,
  },
  //   Sports & Active Wear
  {
    name: "Sports & Active Wear",
    categoryId: "women_sports_and_active_wear",
    parentCategoryName: "Sports & Active Wear",
    parentCategoryId: "women_sports_and_active_wear",
    level: 3,
  },
  {
    name: "Clothing",
    categoryId: "women_clothing",
    parentCategoryName: "Sports & Active Wear",
    parentCategoryId: "women_sports_and_active_wear",
    level: 3,
  },
  {
    name: "Footwear",
    categoryId: "women_sports_footwear",
    parentCategoryName: "Sports & Active Wear",
    parentCategoryId: "women_sports_and_active_wear",
    level: 3,
  },
  {
    name: "Sports Accessories",
    categoryId: "women_sports_accessories",
    parentCategoryName: "Sports & Active Wear",
    parentCategoryId: "women_sports_and_active_wear",
    level: 3,
  },
  {
    name: "Sports Equipment",
    categoryId: "women_sports_equipment",
    parentCategoryName: "Sports & Active Wear",
    parentCategoryId: "women_sports_and_active_wear",
    level: 3,
  },
  //   Lingerie Sleepwear
  {
    name: "Lingerie & Sleepwear",
    categoryId: "women_lingerie_and_sleepwear",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Bra",
    categoryId: "women_bra",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Panty & Underwear",
    categoryId: "women_panty_and_underwear",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Briefs",
    categoryId: "women_briefs",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Shapewear",
    categoryId: "women_shapewear",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Sleepwear & Loungewear",
    categoryId: "women_sleepwear_and_loungewear",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Swimwear",
    categoryId: "women_swimwear",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  {
    name: "Camisoles & Thermals",
    categoryId: "women_camisoles_and_thermals",
    parentCategoryName: "Lingerie & Sleepwear",
    parentCategoryId: "women_lingerie_and_sleepwear",
    level: 3,
  },
  // Jewellery & Accessories
  {
    name: "Handbags & Clutches",
    categoryId: "women_fashion_handbags_clutches",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Necklaces",
    categoryId: "women_fashion_necklaces",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Earrings",
    categoryId: "women_fashion_earrings",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Rings",
    categoryId: "women_fashion_rings",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Bracelets",
    categoryId: "women_fashion_bracelets",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Bangles",
    categoryId: "women_fashion_bangles",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Pendants",
    categoryId: "women_fashion_pendants",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Anklets",
    categoryId: "women_fashion_anklets",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Hair Accessories",
    categoryId: "women_fashion_hair_accessories",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Sunglasses",
    categoryId: "women_fashion_sunglasses",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Watches & Wearables",
    categoryId: "women_fashion_watches_wearables",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Belts",
    categoryId: "women_fashion_belts",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },
  {
    name: "Scarves & Stoles",
    categoryId: "women_fashion_scarves_stoles",
    parentCategoryName: "Women Jewellery & Accessories",
    parentCategoryId: "women_jewellery_and_accessories",
    level: 3,
  },

  // 💄 Women Makeup
  {
    name: "Foundation",
    categoryId: "women_makeup_foundation",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Primer",
    categoryId: "women_makeup_primer",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Concealer",
    categoryId: "women_makeup_concealer",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Compact",
    categoryId: "women_makeup_compact",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Blush",
    categoryId: "women_makeup_blush",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Highlighter",
    categoryId: "women_makeup_highlighter",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Bronzer",
    categoryId: "women_makeup_bronzer",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Kajal",
    categoryId: "women_makeup_kajal",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Eyeliner",
    categoryId: "women_makeup_eyeliner",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Mascara",
    categoryId: "women_makeup_mascara",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Eyeshadow",
    categoryId: "women_makeup_eyeshadow",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Eyebrow Products",
    categoryId: "women_makeup_eyebrow",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Lipstick",
    categoryId: "women_makeup_lipstick",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Lip Gloss",
    categoryId: "women_makeup_lip_gloss",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Lip Liner",
    categoryId: "women_makeup_lip_liner",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Lip Balm",
    categoryId: "women_makeup_lip_balm",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Nail Polish",
    categoryId: "women_makeup_nail_polish",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Nail Art & Remover",
    categoryId: "women_makeup_nail_art_remover",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Makeup Kits & Combos",
    categoryId: "women_makeup_kits_combos",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
  {
    name: "Makeup Tools & Brushes",
    categoryId: "women_makeup_tools_brushes",
    parentCategoryName: "Women Makeup",
    parentCategoryId: "women_makeup",
    level: 3,
  },
];
