// Standard Double-Entry Ledger Chart of Accounts
export const LedgerAccountType = Object.freeze({
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  EQUITY: "EQUITY",
  REVENUE: "REVENUE",
  EXPENSE: "EXPENSE",
});

export const LedgerAccount = Object.freeze({
  // Customer Balances (Liabilities to Platform)
  CUSTOMER_WALLET: "CUSTOMER_WALLET",
  CUSTOMER_ESCROW: "CUSTOMER_ESCROW",
  CUSTOMER_FUNDS: "CUSTOMER_FUNDS",
  CUSTOMER_PROMOTIONAL_CREDIT: "CUSTOMER_PROMOTIONAL_CREDIT",

  // Gateway & Bank Settlement (Assets to Platform)
  GATEWAY_CLEARING: "GATEWAY_CLEARING",
  BANK_ESCROW: "BANK_ESCROW",
  BANK_RECONCILIATION: "BANK_RECONCILIATION",
  PAYOUT_SETTLED: "PAYOUT_SETTLED",

  // Vendor Payouts & Reserves (Liabilities to Platform)
  SELLER_PAYABLE: "SELLER_PAYABLE",
  SELLER_RESERVE: "SELLER_RESERVE",
  PAYOUT_PENDING: "PAYOUT_PENDING",
  REFUND_LIABILITY: "REFUND_LIABILITY",

  // Commercial Platform Earnings (Revenue to Platform)
  PLATFORM_COMMISSION_REVENUE: "PLATFORM_COMMISSION_REVENUE",
  PLATFORM_REVENUE: "PLATFORM_REVENUE",
  PAYMENT_SURCHARGE_REVENUE: "PAYMENT_SURCHARGE_REVENUE",

  // Operational Expenses
  GATEWAY_PROCESSING_FEE_EXPENSE: "GATEWAY_PROCESSING_FEE_EXPENSE",
  GATEWAY_FEE_EXPENSE: "GATEWAY_FEE_EXPENSE",
  GATEWAY_FEES: "GATEWAY_FEES",
  PROMOTIONAL_DISCOUNT_EXPENSE: "PROMOTIONAL_DISCOUNT_EXPENSE",

  // Tax Liabilities
  TAX_COLLECTED_TCS: "TAX_COLLECTED_TCS",
  TAX_COLLECTED_TDS: "TAX_COLLECTED_TDS",
  TAX_PAYABLE: "TAX_PAYABLE",

  // Suspense / Transit & Disputes
  REFUND_SUSPENSE: "REFUND_SUSPENSE",
  CHARGEBACK_DISPUTE: "CHARGEBACK_DISPUTE",
});

export const EntryType = Object.freeze({
  DEBIT: "DEBIT",
  CREDIT: "CREDIT",
});

export const FinancialEvent = Object.freeze({
  ORDER_PAYMENT_CAPTURED: "ORDER_PAYMENT_CAPTURED",
  WALLET_TOPUP: "WALLET_TOPUP",
  WALLET_DEBIT: "WALLET_DEBIT",
  WALLET_REFUND: "WALLET_REFUND",
  GATEWAY_REFUND: "GATEWAY_REFUND",
  SELLER_SETTLEMENT: "SELLER_SETTLEMENT",
  PROMOTIONAL_CREDIT: "PROMOTIONAL_CREDIT",
  DISPUTE_REVERSAL: "DISPUTE_REVERSAL",
  CHARGEBACK_FILED: "CHARGEBACK_FILED",
  CHARGEBACK_LOST: "CHARGEBACK_LOST",
  CHARGEBACK_WON: "CHARGEBACK_WON",
  PAYOUT_INITIATED: "PAYOUT_INITIATED",
  PAYOUT_SETTLED: "PAYOUT_SETTLED",
  SELLER_RESERVE_HOLD: "SELLER_RESERVE_HOLD",
  SELLER_RESERVE_RELEASE: "SELLER_RESERVE_RELEASE",
});

export default LedgerAccount;

