/**
 * Standard Capability Enums for AI Providers and Models.
 */
export const AICapability = Object.freeze({
  CHAT: "CHAT",
  STREAMING: "STREAMING",
  TOOL_CALLING: "TOOL_CALLING",
  STRUCTURED_OUTPUT: "STRUCTURED_OUTPUT",
  VISION: "VISION",
  LONG_CONTEXT: "LONG_CONTEXT",
  FAST_RESPONSE: "FAST_RESPONSE",
  DEEP_REASONING: "DEEP_REASONING",
  JSON_OUTPUT: "JSON_OUTPUT",
  EMBEDDING: "EMBEDDING",
});

export const TaskType = Object.freeze({
  SHOPPING_ASSISTANT: "SHOPPING_ASSISTANT",
  PRODUCT_COMPARISON: "PRODUCT_COMPARISON",
  REVIEW_SUMMARY: "REVIEW_SUMMARY",
  PRICE_INTELLIGENCE: "PRICE_INTELLIGENCE",
  LISTING_OPTIMIZATION: "LISTING_OPTIMIZATION",
  ADMIN_COPILOT: "ADMIN_COPILOT",
  LOGISTICS_ANALYSIS: "LOGISTICS_ANALYSIS",
  RECOMMENDATION: "RECOMMENDATION",
  VISUAL_SEARCH: "VISUAL_SEARCH",
});
