export const ShipmentStatus = Object.freeze({
  CREATED: "CREATED",
  ALLOCATED: "ALLOCATED",
  PICKING: "PICKING",
  PICKED: "PICKED",
  PACKING: "PACKING",
  PACKED: "PACKED",
  READY_FOR_DISPATCH: "READY_FOR_DISPATCH",
  DISPATCHED: "DISPATCHED",
  IN_TRANSIT: "IN_TRANSIT",
  AT_HUB: "AT_HUB",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  DELIVERY_FAILED: "DELIVERY_FAILED",
  DELAYED: "DELAYED",
  RETURN_IN_PROGRESS: "RETURN_IN_PROGRESS",
  RETURNED_TO_ORIGIN: "RETURNED_TO_ORIGIN",
  CANCELLED: "CANCELLED",
});

export const VALID_SHIPMENT_TRANSITIONS = {
  CREATED: ["ALLOCATED", "PICKING", "CANCELLED"],
  ALLOCATED: ["PICKING", "CANCELLED"],
  PICKING: ["PICKED", "CANCELLED"],
  PICKED: ["PACKING", "PACKED", "CANCELLED"],
  PACKING: ["PACKED", "CANCELLED"],
  PACKED: ["READY_FOR_DISPATCH", "DISPATCHED", "CANCELLED"],
  READY_FOR_DISPATCH: ["DISPATCHED", "CANCELLED"],
  DISPATCHED: ["IN_TRANSIT", "AT_HUB", "DELAYED"],
  IN_TRANSIT: ["AT_HUB", "OUT_FOR_DELIVERY", "DELAYED", "RETURN_IN_PROGRESS"],
  AT_HUB: ["IN_TRANSIT", "OUT_FOR_DELIVERY", "DELAYED", "RETURN_IN_PROGRESS"],
  OUT_FOR_DELIVERY: ["DELIVERED", "DELIVERY_FAILED", "DELAYED", "RETURN_IN_PROGRESS"],
  DELIVERY_FAILED: ["OUT_FOR_DELIVERY", "AT_HUB", "RETURN_IN_PROGRESS"],
  DELAYED: ["IN_TRANSIT", "AT_HUB", "OUT_FOR_DELIVERY", "DELIVERED", "RETURN_IN_PROGRESS"],
  RETURN_IN_PROGRESS: ["AT_HUB", "RETURNED_TO_ORIGIN"],
  RETURNED_TO_ORIGIN: [],
  DELIVERED: ["RETURN_IN_PROGRESS"],
  CANCELLED: [],
};

export const ServiceLevel = Object.freeze({
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
  SAME_DAY: "SAME_DAY",
});

export const ShipmentPriority = Object.freeze({
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  URGENT: "URGENT",
});

export const SlaStatus = Object.freeze({
  ON_TRACK: "ON_TRACK",
  AT_RISK: "AT_RISK",
  BREACHED: "BREACHED",
  COMPLETED: "COMPLETED",
});

export const AgentStatus = Object.freeze({
  AVAILABLE: "AVAILABLE",
  ASSIGNED: "ASSIGNED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  ON_BREAK: "ON_BREAK",
  OFFLINE: "OFFLINE",
  SUSPENDED: "SUSPENDED",
});

export const HubType = Object.freeze({
  FULFILLMENT_CENTER: "FULFILLMENT_CENTER",
  PRIMARY_HUB: "PRIMARY_HUB",
  SORT_CENTER: "SORT_CENTER",
  LAST_MILE_HUB: "LAST_MILE_HUB",
});

export const HubStatus = Object.freeze({
  ACTIVE: "ACTIVE",
  CONGESTED: "CONGESTED",
  MAINTENANCE: "MAINTENANCE",
  INACTIVE: "INACTIVE",
});

export const ExceptionType = Object.freeze({
  ADDRESS_ISSUE: "ADDRESS_ISSUE",
  CUSTOMER_UNAVAILABLE: "CUSTOMER_UNAVAILABLE",
  FAILED_DELIVERY: "FAILED_DELIVERY",
  WRONG_ADDRESS: "WRONG_ADDRESS",
  PACKAGE_DAMAGED: "PACKAGE_DAMAGED",
  PACKAGE_MISSING: "PACKAGE_MISSING",
  HUB_DELAY: "HUB_DELAY",
  VEHICLE_ISSUE: "VEHICLE_ISSUE",
  AGENT_UNAVAILABLE: "AGENT_UNAVAILABLE",
  ROUTE_DEVIATION: "ROUTE_DEVIATION",
  PAYMENT_COD_ISSUE: "PAYMENT_COD_ISSUE",
});

export const ExceptionStatus = Object.freeze({
  DETECTED: "DETECTED",
  ASSIGNED: "ASSIGNED",
  INVESTIGATING: "INVESTIGATING",
  ACTION_REQUIRED: "ACTION_REQUIRED",
  RESOLVED: "RESOLVED",
});

export const ManifestType = Object.freeze({
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
  LAST_MILE_DISPATCH: "LAST_MILE_DISPATCH",
});

export const ManifestStatus = Object.freeze({
  OPEN: "OPEN",
  SEALED: "SEALED",
  DISPATCHED: "DISPATCHED",
  RECEIVED: "RECEIVED",
  CLOSED: "CLOSED",
});
